include ../../common_mk/flags.mk

# Source files
SRCS = $(wildcard *.cpp)

# Include directories
INCS = -I../Common -I$${HOME}/protobuf/src -I$${HOME}/abseil-cpp

include ../../common_mk/files.mk

include ../../common_mk/rules.mk

include ../../common_mk/targets.mk
