include ../../common_mk/flags.mk

# Source files
SRCS = *.cpp

# Include directories
INCS = -I../Common -I~/protobuf/src/google/protobuf

include ../../common_mk/files.mk

include ../../common_mk/rules.mk

include ../../common_mk/targets.mk
