include ../../common_mk/flags.mk

# Target executable
TARGET := train

# Source files
SRCS := train.cpp computeExperts.cpp ../Common/*.cpp

# Include directories
INCS := -I../Common -I~/protobuf/src

include ../../common_mk/files.mk

include ../../common_mk/rules.mk

include ../../common_mk/targets.mk
